In [1]:
import tensorflow as tf
hello = tf.constant("hello Tensorflow!")
sess = tf.Session()

print(sess.run(hello))


b'hello Tensorflow!'


In [3]:
x = 1
y = x + 9
print(y)
import tensorflow as tf
x = tf.constant(1,name='x')
x = tf.Variable(x+9,name='y')
print(y)


10
10


In [19]:
# 1-dimension tensor

import numpy as np
tensor_1d = np.array([1.3, 1, 4.0, 23.99])
print(tensor_1d)
print(tensor_1d[0])
print(tensor_1d[2])
print("====")

x = 3
print(x)
print("x = ",x)

# rank of tensor
#print("tensor_1d.ndim = ", tensor_1d.ndim)

# tuple
print("tensor_1d.shape = ", tensor_1d.shape)

# data type
print("tensor_1d.dtype = ", tensor_1d.dtype)




[  1.3    1.     4.    23.99]
1.3
4.0
====
3
x =  3
tensor_1d.shape =  (4,)
tensor_1d.dtype =  float64


In [31]:
# 2-dimension tensor

import numpy as np
tensor_2d = np.array([(1,2,3,4),
                      (4,5,6,7),
                      (5,6,7,8),
                      (12,13,15,16)])
print(tensor_2d)
print(tensor_2d[2][3])
print(tensor_2d[0][1])
print(tensor_2d[0:3][1])
print(tensor_2d[0:3][2])
print(tensor_2d[0:3][1:2])
print(tensor_2d[0:3,1:2])

SyntaxError: invalid syntax (<ipython-input-31-e73ee1cd3ee6>, line 14)

In [33]:
import tensorflow as tf
import numpy as np
matrix1 = np.array([(2,2,2),(2,2,2),(2,2,2)],dtype='int32')
matrix2 = np.array([(1,1,1),(1,1,1),(1,1,1)],dtype='int32')

print("matrix1 = ", matrix1)
print("matrix2 = ", matrix2)

matrix1 = tf.constant(matrix1)
matrix2 = tf.constant(matrix2)

print("matrix1 = ", matrix1)
print("matrix2 = ", matrix2)

matrix_product = tf.matmul(matrix1, matrix2)
matrix_sum = tf.add(matrix1,matrix2)


matrix1 =  [[2 2 2]
 [2 2 2]
 [2 2 2]]
matrix2 =  [[1 1 1]
 [1 1 1]
 [1 1 1]]
tf.matrix1 =  Tensor("Const_1:0", shape=(3, 3), dtype=int32)
tf.matrix2 =  Tensor("Const_2:0", shape=(3, 3), dtype=int32)
